### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by PLoic** [dldl/sphinx-server#21]
To execute the curl command properly, you need to add the user parameters like this :
https://github.com/travis-ci/travis-ci/issues/6478
Or we need to stay under our limits: 
https://developer.github.com/v3/#rate-limiting

**Comment by quentinus95** [comment]
This issue doesn't seems to be related to the API limit as it should be a HTTP 403. Here, network seems to be buggy.

It may be Docker related (I have try a lot of fixes without any success, see commits fa26e1f865d11aa5ef0a3a915b56f2012aab4f58 to bbd2d857249c92a06b2276d633cd066f677762cf).

**Comment by PLoic** [comment]
I will investigate on that subject
