### ISSUE TITLE
Ignore section  not take in count

### ISSUE THREAD

**Issue by PLoic** [dldl/sphinx-server#24]
The ignore section of yml file looks not take in count by the server.

**Comment by quentinus95** [comment]
Can you give a process to reproduce the issue?

**Comment by PLoic** [comment]
Just check you have ".git/" in the ignore section of the conf file, and do "docker logs -f" on your container you will see a new build each time the ".git/.lock" change

**Comment by PLoic** [comment]
Solved by #25
