### ISSUE TITLE
Add support of latex

### ISSUE THREAD

**Issue by PLoic** [dldl/sphinx-server#27]

**Comment by PLoic** [comment]
@quentinus95 Can we intergrate compil.io cli with this project ?

**Comment by quentinus95** [comment]
This may be doable but you need to find out which commands are required first. Can you have a look?

**Comment by PLoic** [comment]
@quentinus95 I will do that

**Comment by quentinus95** [comment]
Because compil.io is not available anymore, I guess we can close this issue.
