### ISSUE TITLE
Simplified Chinese nonsupport

### ISSUE THREAD

**Issue by zhongzhq** [dldl/sphinx-server#32]
![plantuml-f628fef4a61a0f6ec6f382a11cc40ee65bc8e0c3](https://user-images.githubusercontent.com/826607/52679361-d43aa800-2f6f-11e9-90e0-0e09cd065d61.png)

**Comment by zhongzhq** [comment]
java -jar plantuml.jar -charset utf-8 -tsvg test.uml

http://oohcode.com/2013/12/29/plantuml-chinese-garbled/

**Comment by quentinus95** [comment]
Add to your `conf.py`:

```py
plantuml = 'java -jar /opt/plantuml.jar -tsvg -charset utf-8'
plantuml_output_format = 'svg'
```

More info here: https://github.com/sphinx-contrib/plantuml/
