### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by sp1thas** [dldl/sphinx-server#34]
do you have any plans to support Python 3?

My current project is implemented in Python 3.6 and sphinx-server can't handle things like type hints.

I would like to contribute in order to make sphinx-server compatible with python 3.

**Comment by quentinus95** [comment]
Hi @sp1thas,

If you want to open a pull request, it'll help. I don't see any blocker for migrating the project to Python 3.

I would list the changes to be:
- change the base image from the current Alpine to an official Python 3 Alpine in the Dockerfile (e.g. `python:3.8.0-alpine3.10`)
- run 2to3 on the .py file
- regenerate the requirements file
- the Travis configuration file uses an image based on Python 2.7, but we actually need and use only Docker

**Comment by quentinus95** [comment]
Fixed with #35.
